// Disposable/temporary email domain blocklist
// These domains provide throwaway emails used for fake signups
// Update periodically — new disposable services pop up regularly

export const DISPOSABLE_DOMAINS = new Set([
  // Major disposable email services
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org", "guerrillamail.de",
  "guerrillamailblock.com", "grr.la", "sharklasers.com", "guerrilla.ml",
  "10minutemail.com", "10minutemail.net", "10minutemail.org", "10mail.org",
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempmail.net", "tempail.com",
  "throwaway.email", "throwaway.cc", "throwamail.com",
  "mailinator.com", "mailinator.net", "mailinator.org", "mailinator2.com",
  "maildrop.cc", "maildrop.gq", "maildrop.ml",
  "yopmail.com", "yopmail.fr", "yopmail.net", "yopmail.gq",
  "dispostable.com", "disposableemailaddresses.emailmiser.com",
  "trashmail.com", "trashmail.me", "trashmail.net", "trashmail.org",
  "fakeinbox.com", "fakemail.net", "fakemail.fr",
  "getnada.com", "nada.email", "nada.lt",
  "mailnesia.com", "mailnesia.net",
  "tempinbox.com", "tempinbox.xyz",
  "discard.email", "discardmail.com", "discardmail.de",
  "mohmal.com", "mohmal.im", "mohmal.in",
  "harakirimail.com", "tmail.ws", "burnermail.io",
  "sharklasers.com", "spam4.me", "spamgourmet.com",
  "trashymail.com", "trashymail.net",
  "mailcatch.com", "mailscrap.com",
  "mytemp.email", "mytrashmail.com",
  "jetable.org", "jetable.com", "jetable.net",
  "safetymail.info", "safetypost.de",
  "spambox.us", "spamfree24.org", "spamhole.com",
  "tempr.email", "tempmailaddress.com",
  "emailondeck.com", "emailtemporario.com.br",
  "crazymailing.com", "tmail.link",
  "tmpmail.net", "tmpmail.org",
  "20minutemail.com", "33mail.com",
  "mailforspam.com", "maileater.com",
  "mailexpire.com", "mailmoat.com",
  "mailnull.com", "mailshell.com",
  "mailzilla.com", "meltmail.com",
  "mintemail.com", "mt2015.com",
  "nobulk.com", "nogmailspam.info",
  "nomail.xl.cx", "nospam.ze.tc",
  "owlpic.com", "proxymail.eu",
  "rcpt.at", "reallymymail.com",
  "recode.me", "regbypass.com",
  "rmqkr.net", "royal.net",
  "rtrtr.com", "s0ny.net",
  "safe-mail.net", "safersignup.de",
  "shortmail.net", "sibmail.com",
  "skeefmail.com", "slaskpost.se",
  "slipry.net", "snakemail.com",
  "sofort-mail.de", "solvemail.info",
  "soodomail.com", "soodonims.com",
  "spam.la", "spamavert.com",
  "spambob.net", "spambog.com",
  "spamcero.com", "spamday.com",
  "spamex.com", "spamfighter.cf",
  "spamfighter.ga", "spamfighter.gq",
  "spamfighter.ml", "spamfighter.tk",
  "tempomail.fr", "temporaryemail.net",
  "temporaryemail.us", "temporaryforwarding.com",
  "temporaryinbox.com", "temporarymailaddress.com",
  "thankyou2010.com", "thisisnotmyrealemail.com",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "wh4f.org", "whyspam.me",
  "willhackforfood.biz", "willselfdestruct.com",
  "yepmail.net", "yogamaven.com",
  "zehnminutenmail.de", "zoemail.org",
  "zzz.com", "emailfake.com", "cuvox.de",
  "armyspy.com", "dayrep.com", "einrot.com",
  "fleckens.hu", "gustr.com", "jourrapide.com",
  "rhyta.com", "superrito.com", "teleworm.us",
  // Russian/Asian disposable
  "mailfa.tk", "mail-temporaire.fr", "mail-tester.com",
  "tempsky.com", "tempemail.co", "tempemail.net",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}
