import type { Metadata } from 'next';
import { FeaturePageLayout } from '@/components/FeaturePageLayout';

export const metadata: Metadata = {
  title: 'One-Click Listing — List Amazon Products on eBay in 60 Seconds',
  description: 'See a product on Amazon? One click lists it on eBay with AI title, description, images, and pricing. The fastest way to dropship.',
  keywords: ['one click ebay listing', 'amazon to ebay listing', 'quick ebay listing tool', 'fast ebay lister', 'instant ebay listing'],
};

export default function OneClickListingPage() {
  return (
    <FeaturePageLayout
      badge="SPEED"
      badgeColor="bg-[#F59E0B]/15 text-[#F59E0B] border border-[#F59E0B]/20"
      title="One-Click Listing"
      subtitle="See it on Amazon. Click once. Listed on eBay. 60 seconds."
      heroDescription="When you are browsing Amazon and spot a product worth selling on eBay, you should not need to copy data, switch tabs, fill forms, and upload images manually. With UnicornDS, a floating panel appears on every Amazon product page showing the Demand Score, profit calculation, competitor price bar, and VERO check status. If everything looks good, click List on eBay and the extension handles everything: opens eBay, generates an AI title, writes a description, uploads images, fills item specifics, sets the price, and submits. One click, 60 seconds, listed."
      screenshotAlt="UnicornDS overlay on Amazon product page with one-click listing button"
      sections={[
        { icon: '⚡', title: 'Instant Overlay', description: 'A floating panel appears on every Amazon product page. See demand score, profit, competition, and VERO status at a glance.' },
        { icon: '💰', title: 'Profit Calculator', description: 'Shows your exact profit after eBay fees, promo fees, and shipping. Green means profitable, red means skip it.' },
        { icon: '📊', title: 'Competitor Price Bar', description: 'See what other eBay sellers charge for the same product. Lowest, average, highest, and suggested undercut price.' },
        { icon: '🛡️', title: 'Pre-Check Safety', description: 'VERO check, compliance check, and profit check all happen before you click. Only safe, profitable products get listed.' },
        { icon: '🤖', title: 'AI-Generated Content', description: 'Title, description, and item specifics are generated by GPT-4o. No manual writing needed.' },
        { icon: '🔍', title: 'Check on eBay', description: 'Before listing, check if competitors already sell this on eBay by EAN/UPC for exact matches or keywords for broader results.' },
      ]}
      howItWorks={[
        'Browse Amazon normally. On every product page, the UnicornDS overlay appears automatically showing key metrics.',
        'Check the Demand Score, profit calculation, and competitor prices. Decide in seconds whether this product is worth listing.',
        'Click "List on eBay". The extension opens eBay and fills everything: AI title, description, images, price, specs.',
        'Review the listing if you want (or let it submit automatically if auto-approve is enabled).',
        'Done. Product is live on eBay. Move on to the next one.',
      ]}
      ctaText="Start listing in one click"
    />
  );
}
